name: Laravel

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    env:
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      redis:
        image: redis
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:

    # SETUP PHP
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug
    
    # CHECKOUT
    - uses: actions/checkout@v2
    
    # Copy .env
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    # Install Dependencies with composer install
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    # The usual generate key
    - name: Generate key
      run: php artisan key:generate

    # Clear Configuration Cache
    - name: Clear Config
      run: php artisan config:clear
    
    # Perm settings
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    # Migrate
    - name: Create Database
      run: php artisan migrate -v
      env:
        DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
    
    # Test the system
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit --coverage-text
      env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
